### ISSUE TITLE
DOC: Image on PyPI

### ISSUE THREAD

**Issue by MartinThoma** [michelcrypt4d4mus/pdfalyzer#3]
Hi,

Thank you for creating this project!

I've just noticed that the image url on https://pypi.org/project/pdfalyzer/ is broken. That might be the case if the image is not part of the uploaded package.

**Comment by michelcrypt4d4mus** [comment]
yeah that's why there's a "PyPi Users: This document renders a lot better..." thing near the top. i hadn't spent time trying to fix that because people can just look here on GitHub but I tried what you suggested and managed to include the `doc/` folder in the source file `pdfalyzer-1.11.6.tar.gz`.  Published to PyPi but image links are still broken. oh well.

**Comment by michelcrypt4d4mus** [comment]
I did also at some point try to make the links fully qualified URLs (e.g. https://github.com/michelcrypt4d4mus/pdfalyzer/blob/master/doc/svgs/rendered_images/NMAP_Commands_Cheat_Sheet_and_Tutorial.pdf.rich_table_tree.png)  but that also didn't work.

**Comment by michelcrypt4d4mus** [comment]
I tried most of the approaches [discussed on stackoverflow recently](https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github). none of them worked. i also noticed that the projects of the people who posted the originally working answers no longer display any images on PyPi.

**Comment by michelcrypt4d4mus** [comment]
wait i'm wrong - it actually _is_ working: https://pypi.org/project/pdfalyzer/
I just couldn't see them from some of my browsers
